version: '3.8'

services:
  yt-dlp-api:
    build: .
    ports:
      - "18000:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
